'use client';

import { useState } from 'react';
import { TaskList } from '@/components/tasks';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { TaskStatusBadge } from '@/components/tasks';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';
import {
  Bot,
  Calendar,
  Zap,
  FileText,
  ArrowRight,
  ExternalLink,
} from 'lucide-react';
import type { Task } from '@/types/task';
import { formatTokens } from '@/components/tasks';

export default function DashboardPage() {
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);

  return (
    <div className="flex h-full">
      {/* Task List Panel */}
      <div className="w-[380px] border-r border-border flex-shrink-0">
        <TaskList
          onTaskSelect={setSelectedTask}
          selectedTaskId={selectedTask?.id}
        />
      </div>

      {/* Task Detail Panel */}
      <div className="flex-1 flex flex-col">
        {selectedTask ? (
          <TaskDetailPanel task={selectedTask} />
        ) : (
          <EmptyDetailPanel />
        )}
      </div>
    </div>
  );
}

function TaskDetailPanel({ task }: { task: Task }) {
  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="p-6 border-b border-border">
        <div className="flex items-start justify-between mb-4">
          <div className="flex-1 min-w-0 pr-4">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-sm font-mono text-muted-foreground">
                #{String(task.id).slice(-6)}
              </span>
              <TaskStatusBadge status={task.status} />
            </div>
            <h1 className="text-xl font-semibold mb-2">{task.description}</h1>
          </div>
          <Button variant="outline" size="sm" className="gap-2 shrink-0">
            <ExternalLink className="h-4 w-4" />
            Open in Workbench
          </Button>
        </div>

        {/* Meta Info */}
        <div className="flex items-center gap-6 text-sm text-muted-foreground">
          <div className="flex items-center gap-2">
            <Bot className="h-4 w-4" />
            <span className="capitalize">{task.agent_name}</span>
          </div>
          <div className="flex items-center gap-2">
            <Calendar className="h-4 w-4" />
            <span>{new Date(task.created_at).toLocaleString()}</span>
          </div>
          {task.total_tokens_used > 0 && (
            <div className="flex items-center gap-2 text-yellow-500">
              <Zap className="h-4 w-4" />
              <span>{formatTokens(task.total_tokens_used)} tokens</span>
              <span className="text-muted-foreground">
                (${task.total_cost.toFixed(4)})
              </span>
            </div>
          )}
        </div>
      </div>

      {/* Content */}
      <ScrollArea className="flex-1 p-6">
        <div className="space-y-6">
          {/* Error Message */}
          {task.status === 'failed' && task.error_message && (
            <Card className="border-red-500/20 bg-red-500/5">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm text-red-500">Error</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm">{task.error_message}</p>
              </CardContent>
            </Card>
          )}

          {/* Archive Summary */}
          {task.is_archived && task.archive_summary && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm flex items-center gap-2">
                  <FileText className="h-4 w-4" />
                  Summary
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm whitespace-pre-wrap">{task.archive_summary}</p>
              </CardContent>
            </Card>
          )}

          {/* Artifacts */}
          {task.archive_artifacts && task.archive_artifacts.length > 0 && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">Artifacts</CardTitle>
                <CardDescription>Files generated by this task</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {task.archive_artifacts.map((artifact, index) => (
                    <div
                      key={index}
                      className="flex items-center gap-2 p-2 rounded-md bg-secondary/50 text-sm font-mono"
                    >
                      <FileText className="h-4 w-4 text-muted-foreground" />
                      {artifact}
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Task Details */}
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm">Task Details</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <dt className="text-muted-foreground">Task ID</dt>
                  <dd className="font-mono">{task.id}</dd>
                </div>
                <div>
                  <dt className="text-muted-foreground">User ID</dt>
                  <dd className="font-mono">{task.user_id}</dd>
                </div>
                <div>
                  <dt className="text-muted-foreground">Created</dt>
                  <dd>{new Date(task.created_at).toLocaleString()}</dd>
                </div>
                <div>
                  <dt className="text-muted-foreground">Updated</dt>
                  <dd>{new Date(task.updated_at).toLocaleString()}</dd>
                </div>
                {task.archived_at && (
                  <div>
                    <dt className="text-muted-foreground">Archived</dt>
                    <dd>{new Date(task.archived_at).toLocaleString()}</dd>
                  </div>
                )}
              </dl>
            </CardContent>
          </Card>

          {/* Placeholder for events/conversation */}
          <Card className="border-dashed">
            <CardContent className="py-8 text-center text-muted-foreground">
              <p className="text-sm">Task conversation history coming in Phase 3...</p>
            </CardContent>
          </Card>
        </div>
      </ScrollArea>
    </div>
  );
}

function EmptyDetailPanel() {
  return (
    <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground">
      <Bot className="h-16 w-16 mb-4 opacity-20" />
      <h2 className="text-lg font-medium mb-2">No Task Selected</h2>
      <p className="text-sm">Select a task from the list to view details</p>
    </div>
  );
}
